---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: ${ECR_REPOSITORY_URI}
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
      serviceAccountName: eks-fargate-sa
