---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: staging
spec:
  selector:
    app: demo-app
  ports:
    - name: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
